### ISSUE TITLE
Bot seems to miss some messages

### ISSUE THREAD

**Issue by TeH-BaK** [spikeydragoon/Cross-Ark-Chat#19]
Mostly the bot works as expected, but i'm noticing randomly some messages the bot isn't pushing through to the discord, I have checked the logs and they are definitely logged in them, but the bot seems to not repeat them all into the discord. (This is using the setting whereby all messages in global are pushed into the discord.)

I have tried some things like changing the rcon chat buffer length and deleting the logs, but this issue seems to persist, it also seems to effect the commands, so they do not work occasionally.

Do you have any suggestions as to maybe server settings that I might have that is causing some compatibility issues? Or any other insights?

**Comment by spikeydragoon** [comment]
If i had to guess a command might be getting stuck rcon wise which is holding discord up so message is getting dropped. How many servers do you have running on the bot?

**Comment by TeH-BaK** [comment]
Its currently running 5 servers on a cluster, so that's one less than all the official maps released.

**Comment by spikeydragoon** [comment]
Yeah that wouldnt lag it. Can you send your config file. Just delete the password and bot token out.

**Comment by TeH-BaK** [comment]
https://pastebin.com/TAfx92r1

I'm glad it shouldn't, I was hoping to add more servers from another cluster.

**Comment by TeH-BaK** [comment]
If I've over censored that, I can redo it, but its posting most of the messages into different channels, if that effects anything.

**Comment by spikeydragoon** [comment]
Nah we have people with 100-200 servers hooked up that is about only way to get slight delays. Config wise everything looks good so problem might just be it getting delayed when connecting to the servers to send a message. Also it might work better of you use the lan IP instead of the localhost is one thing to try. There are a few more things but it's a bit much to type on phone so will have to wait till I get back home tonight.

**Comment by spikeydragoon** [comment]
Did the lan ip fix anything? Back now but didnt see any messages if you figured it out or not. Also something i forgot to ask was are you running any other programs, mods, or plugins that use rcon or can see messages since that could cause the same issue.

**Comment by TeH-BaK** [comment]
I'm not using any other rcon programs concurrently, as mostly the cross ark chat replaces what I use rcon for (player connection and global chat activity). Pretty sure none of my mods use rcon and plugins? I assume you mean things like ark server API's, which i do not, as i'm running on linux, I think that is not an option.

Interestingly the bot never seems to miss people connecting or disconnecting from the server (I've never had a leave and no join message or vice versa, nor noticed a player on a server which the bot has not announced, coincidence or not, i'm not certain, but this might be a related symptom.

I've currently not tried using the LAN IP, because as the server runs in a datacentre, finding it would likely be problematic. But i'm guessing from our previous discussion, I could try using the web IP. I was actually holding out for the more things to try, as i'm pretty certain its not a connection issue, as I've noticed previously when the bot loses connection to the server it does not reconnect, and i must restart the service (When the bot disconnects is announces all players leaving the server, and is obvious). (I've accidently caused this before by creating excessive server lag.)

**Comment by spikeydragoon** [comment]
Ah yeah in a data center most use the public ip since their routers auto route back properly.

Yeah if the dc and connect doesnt miss they its 100% discord getting stuck and dropping messages.

I had that happen once today since discord was acting up however its normally not an issue. To completely fix the issue i will have to update the discord reading/sending side i was planning to wait until i finish the new bot however due to it happening more lately i will probably just go ahead and update this version to have the fix.

One thing to check tho is it still sending to other servers correctly and only discord side is dropping? Also check the logs the bot puts out since it should show all messages even if it was dropped by discord. That will give me some more info on if its only discord side or if its code dropping it somewhere do to a non caught error.

**Comment by TeH-BaK** [comment]
It's not easy for me to test that its sending to all servers correctly. 

I have to say though. i'm not convinced. as the commands stop working, and i'd assume that doesn't use discord to do the responses, but it also doesn't seem to be logging much of any chat; but discord errors and rcon errors are aplenty.

The rcon errors logfile is full of short descriptionless "input/output error" and a few of these:

`01:22:21 System.IO.IOException: Input/output error
   at System.ConsolePal.Write(SafeFileHandle fd, Byte* bufPtr, Int32 count)
   at System.ConsolePal.Write(SafeFileHandle fd, Byte[] buffer, Int32 offset, Int32 count)
   at System.ConsolePal.UnixConsoleStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.WriteLine(String value)
   at System.IO.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
   at CrossArkChat.CrossDiscordChatHandler.OnMessageReceivedAsync(SocketMessage message)
01:22:28 System.IO.IOException: Input/output error
   at System.ConsolePal.Write(SafeFileHandle fd, Byte* bufPtr, Int32 count)
   at System.ConsolePal.Write(SafeFileHandle fd, Byte[] buffer, Int32 offset, Int32 count)
   at System.ConsolePal.UnixConsoleStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.WriteLine(String value)
   at System.IO.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
   at CrossArkChat.CrossDiscordChatHandler.OnMessageReceivedAsync(SocketMessage message)
01:23:39 System.IO.IOException: Input/output error
   at System.ConsolePal.Write(SafeFileHandle fd, Byte* bufPtr, Int32 count)
   at System.ConsolePal.Write(SafeFileHandle fd, Byte[] buffer, Int32 offset, Int32 count)
   at System.ConsolePal.UnixConsoleStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.WriteLine(String value)
   at System.IO.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
   at CrossArkChat.CrossDiscordChatHandler.OnMessageReceivedAsync(SocketMessage message)`

And the discord log is full of these:

`12:35:26 [Warning] Gateway: System.Exception: WebSocket connection was closed ---> System.Net.WebSockets.WebSocketException: The remote party closed the WebSocket connection without completing the close handshake. ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadBufferedAsyncCore(Memory`1 destination)
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   --- End of inner exception stack trace ---
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Discord.Net.WebSockets.DefaultWebSocketClient.RunAsync(CancellationToken cancelToken)
   --- End of inner exception stack trace ---
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()`

**Comment by spikeydragoon** [comment]
Yeah i noticed today im getting a ton of the same errors so i think discord is acting up or has changed something with their api that i need to update in my code. Ill be looking into whats causing this and pushing out a fix since i can see it on my side as well.

Added it to the bug list https://github.com/spikeydragoon/Cross-Ark-Chat/projects/1 Once i get a fix out ill let you know for testing no eta at this time.

**Comment by spikeydragoon** [comment]
@TeH-BaK This should be fixed in version 5.7 give that a try and let me know how it works.

**Comment by spikeydragoon** [comment]
No reply so going to assume its fixed, if not reopen ticket.

**Comment by TeH-BaK** [comment]
For some reason I wasn't getting email notifications till that last message. I was waiting on the update. I have installed the new version and will let you know how it goes.

**Comment by spikeydragoon** [comment]
Sounds good.
