### ISSUE TITLE
Upgrade and no way to start 

### ISSUE THREAD

**Issue by gamersalpha** [spikeydragoon/Cross-Ark-Chat#23]
Hello there, 
so i m using Cross ark chat on ubuntu 18.04 LTS
so i update and now i can't start mu bot.

i found this error on the log files : 
```

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Boolean.Parse(String value)
   at CrossArkChat.CrossDiscordChatHandler..ctor(DiscordSocketClient discord, IConfigurationRoot config, LoggingService log, GeneralSettings settings)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at CrossArkChat.Startup.RunAsync()
   at CrossArkChat.Startup.RunAsync(String[] args)
   at CrossArkChat.Program.<Main>(String[] args)
```

what i missed please

**Comment by spikeydragoon** [comment]
Looks like you may have reused the old config since its missing some settings from the config.

Make sure you have all the new settings from the new config or it will not work. If you upgraded from 5.7 then you dont have to change anything in the config however anything older than 5.7 has to use the new config.

**Comment by spikeydragoon** [comment]
Due to no reply assuming fixed, closing issue out.
