### ISSUE TITLE
Discord.Net.HttpException

### ISSUE THREAD

**Issue by SinisterSole** [spikeydragoon/Cross-Ark-Chat#24]
Have these errors when verbose is enabled. Pre 5.7 version (5/8/19) Any help would be appreciated.

2:44:42 Discord.Net.HttpException: The server responded with error 50013: Missing Permissions
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, String endpoint, Object payload, String bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.ModifyGuildChannelAsync(UInt64 channelId, ModifyTextChannelParams args, RequestOptions options)
   at Discord.Rest.ChannelHelper.ModifyAsync(ITextChannel channel, BaseDiscordClient client, Action`1 func, RequestOptions options)
   at CrossArkChat.PlayerCountService.PlayerCountAsync()

**Comment by spikeydragoon** [comment]
@SinisterSole Based on the error message it looks like it doesnt have permission to edit the channel. 
When the player counter is enabled bot must have permissions to edit the channel.

I plan to add permissions checks in the reworked version update so you dont have to guess it will just tell you what discord permissions its missing.

Full list with everything enabled that i can remember is
send
read
embed
manage channel

**Comment by SinisterSole** [comment]
@spikeydragoon Cool. so not a major issue. Nice work BTW. Now if all the other entities would play nice (Steam, Discord), Linux would be THE goto platform for gaming servers :)
