### ISSUE TITLE
little help the bot seems destroyed

### ISSUE THREAD

**Issue by Scaff31** [spikeydragoon/Cross-Ark-Chat#76]
Hello,

Thank you for your work, it's excellent.

I have a problem and would like a little help to know how to debug it.

The bot returns empty when it retrieves information from discord

![image](https://github.com/spikeydragoon/Cross-Ark-Chat/assets/16442430/3fc4ee77-084e-4e16-b721-460d72ee4a84)

Ark Server => Discord = OK
Discord => Ark Server = KO

I modified the _configuration but the bot doesn't seem to want to start again (I'm French and I saw that in the guide parti rcon we didn't use the term 'tribe' but 'tribu' so I modified this part)

It seems that deleting the directory and unzipping the archive again doesn't help (I've gone back to the basic configuration).

Here's the feedback I got:

```
Aug 21 14:05:38 pterodactyl systemd[1]: Stopped Cross Ark Chat Service.
Aug 21 14:05:38 pterodactyl systemd[1]: Started Cross Ark Chat Service.
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]: Unhandled exception. System.FormatException: Could not parse the JSON file.
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]:  ---> System.Text.Json.JsonReaderException: '"' is invalid after a value. Expected either ',', '}', or ']'. LineNumber: 41 | BytePositionInLine: 44.
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]:    at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]:    at System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkipped(Byte marker)
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]:    at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]:    at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]:    at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]:    at System.Text.Json.Utf8JsonReader.Read()
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]:    at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]:    at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]:    at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]:    at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(Stream input)
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]:    at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.Parse(Stream input)
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]:    at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]:    --- End of inner exception stack trace ---
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]:    at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]:    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]: --- End of stack trace from previous location ---
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]:    at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]:    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]:    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]:    at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]:    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]:    at CrossArkChat.Startup..ctor(String[] args) in C:\Dev\Spikeydragoon\Open Source\CrossArkChat\Main\CrossArkChat\Startup.cs:line 55
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]:    at CrossArkChat.Startup.RunAsync(String[] args) in C:\Dev\Spikeydragoon\Open Source\CrossArkChat\Main\CrossArkChat\Startup.cs:line 66
Aug 21 14:05:38 pterodactyl CrossArkChat[60400]:    at CrossArkChat.Program.<Main>(String[] args)
Aug 21 14:05:39 pterodactyl systemd[1]: crossarkchat.service: Main process exited, code=dumped, status=6/ABRT
```

**Comment by Scaff31** [comment]
Ok I found the problem for the bot launch a double quote hidden in the json :) sorry for the inconvenience.

**Comment by spikeydragoon** [comment]
All good if you have anymore issues can reopen ticket.
